version: "3"
services: 
  db:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=hf_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
     - 5432:5432

  api:
    build: ./backend/
    command: yarn dev
    ports:
      - 3333:3333
    volumes:
      - ./backend/:/usr/app
      - /usr/app/node_modules
    depends_on: 
      - db

  frontend:
    build: ./frontend/
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - ./frontend/:/usr/app
      - /usr/app/node_modules
  